version: '3'

services:
  json_rpc:
    restart: on-failure
    build: JSON_RPC/
    command: python JSON_RPC_Server.py
    volumes:
      - ./JSON_RPC/Source:/JSON_RPC
    ports:
      - "${JSON_RPC_PORT}:${JSON_RPC_PORT}"
    environment:
      - JSON_RPC_HOST=${JSON_RPC_HOST}
      - JSON_RPC_PORT=${JSON_RPC_PORT}

  bff_fastapi:
    restart: on-failure
    build: BFF_FASTAPI/
    command: python BFF_FASTAPI_Server.py
    volumes:
      - ./BFF_FASTAPI/Source:/BFF_FASTAPI
    ports:
      - "${BFF_FASTAPI_PORT}:${BFF_FASTAPI_PORT}"
    environment:
      - JSON_RPC_HOST=json_rpc
      - JSON_RPC_PORT=${JSON_RPC_PORT}
      - BFF_FASTAPI_HOST=${BFF_FASTAPI_HOST}
      - BFF_FASTAPI_PORT=${BFF_FASTAPI_PORT}
